# Generated by Django 3.0 on 2019-12-16 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=1024)),
                ('filename', models.CharField(max_length=1024)),
                ('file', models.BinaryField()),
            ],
        ),
    ]
